apiVersion: apps/v1
kind: Deployment
metadata:
  name: Boardgame-deployment
spec:
  selector:
    matchLabels:
      app: Boardgame
  template:
    metadata:
      labels:
        app: Boardgame
    spec:
      containers:
      - name: Boardgame
        image: mukeshr29/boardgameproject:latest
        ports:
        - containerPort: 8080
